// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czlkrbmnqvtnpulcxpkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6bGtyYm1ucXZ0bnB1bGN4cGtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNTAxNzksImV4cCI6MjA3MjkyNjE3OX0.tTifdAJj3DVt9DM9QJgIrwiNAFN1TfKL3-tzk2GMT34";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});